Use ShellCheck to fix issues which are auto-detected

diff --git a/copy/opt/core/bin/check-log b/copy/opt/core/bin/check-log
--- a/copy/opt/core/bin/check-log
+++ b/copy/opt/core/bin/check-log
@@ -12,29 +12,29 @@ lines=5
 
 # Verify parameters and file
 if [[ -z "${file}" ]]; then
-	echo "${0} [file] [lookup] [minimal]"
-	echo
-	echo "OPTIONS:"
-	echo "  file    : path to the filename"
-	echo "  lookup  : regex lookup in file (default: error)"
-	echo "  minimal : number of lines before error reported (default: 1)"
-	exit 1
+    echo "${0} [file] [lookup] [minimal]"
+    echo
+    echo "OPTIONS:"
+    echo "  file    : path to the filename"
+    echo "  lookup  : regex lookup in file (default: error)"
+    echo "  minimal : number of lines before error reported (default: 1)"
+    exit 1
 fi
 if [[ ! -f ${file} ]]; then
-	exit 2
+    exit 2
 fi
 
 # Temporary files required
-tempfile="/var/tmp/$(basename ${file})"
+tempfile="/var/tmp/$(basename "${file}")"
 touch "${tempfile}.current" "${tempfile}.last"
 
 # Lookup
 grep -E "${lookup}" "${file}" | tail -n${lines} > "${tempfile}.current"
 
-if (( $(wc -l < "${tempfile}.current") >= minimal )); then
+if (($(wc -l < "${tempfile}.current") >= minimal)); then
 
-	if ! diff "${tempfile}.last" "${tempfile}.current" >/dev/null 2>&1; then
-		cat "${tempfile}.current" 1>&2
-	fi
+    if ! diff "${tempfile}.last" "${tempfile}.current" > /dev/null 2>&1; then
+        cat "${tempfile}.current" 1>&2
+    fi
 fi
 cat "${tempfile}.current" > "${tempfile}.last"
